### PR TITLE
Add spell checker

### LINKED ISSUE #10: Add spell checker
**Description**
Need of an integrated spellchecker
**Other issues**

### PR DESCRIPTION
**Pull request by Polpetta**
**Reference to the issue**: closes #10 

**Description**
Defined command: `make spellcheck`. Default language: en.

Exceptions can be added in the `dictionati.en.pws` file, one per line.

### CODE REVIEW

**Comment by mzanella** [comment]
Ok per me

**Comment by Polpetta** [comment]
Put your thumb up then :stuck_out_tongue_winking_eye:

**Comment by herrBez** [comment]
I would only add a "how-to-use" in the README, for the rest :+1:

**Comment by Polpetta** [comment]
Will do, not in this branch tho

**Pull request merged**
